pipeline {
  agent any
  environment {
    KUBECONFIG = 'C:\\kubectl\\kubeconfig-minikube.yaml'
  }
  stages {
    stage('Checkout') {
      steps {
        git branch: 'develop', url: 'https://github.com/monanimals/monanimal-extranet.git'
      }
    }
    stage('Deploy to Kubernetes') {
      steps {
        bat 'kubectl apply -k dev/'
      }
    }
  }
}